// Generated by https://quicktype.io

export interface EmpDetail {
  d: D;
}

export interface D {
  results: Result[];
}

export interface Result {
  __metadata?:         Metadata;
  Mandt?:              string;
  EmpId:              string;
  SkillId:            string;
  SkillName:          string;
  CertificateCode:    string;
  ProfLevel:          string;
  CertDate:           string;
  EmpSkillsDataNavig?: EmpSkillsDataNavig;
}

export interface EmpSkillsDataNavig {
  __deferred: Deferred;
}

export interface Deferred {
  uri: string;
}

export interface Metadata {
  id:   string;
  uri:  string;
  type: string;
}
